#-----1.python内置列表操作函数-----
#len(list)用于返回列表元素个数
list1=["Google","Runoob","Taobao"]
print(len(list1))
list2=list(range(5))                    #创建一个范围为0-4的列表
print(len(list2))
#max(list)和min(list)用于返回列表元素的最大值和最小值
#数值列表直接比较数值大小，字符串列表比较字典序，按ascii码大小比较，超出ascii范围的按unicode比较
list1,list2=["Google","Runoob","Taobao"],[456,700,200]
print("list1最大元素值=",max(list1),"list2最大元素值=",max(list2))
print("list1最小元素值=",min(list1),"list2最小元素值=",min(list2))
#-----2.append()&pop()-----
#该函数用于在列表末尾添加新的对象，参数为添加的对象
list1=["Google","Runoob","Taobao"]
list1.append('Baidu')               
print("更新后的列表:",list1)
#队列是一种先进先出(FIFO)的数据结构，可以用列表实现队列的基本功能
#如使用append()向列表末尾添加元素，使用pop()从队列开头删除一个元素并返回
#list.pop(index)，index为指定索引元素，默认为-1，即列表最后一个元素
queue=[]
#添加元素到队列末尾
queue.append("A")
queue.append("B")
queue.append("C")
#从队列开头删除元素并返回
print(queue.pop(0))
print(queue.pop(0))
print(queue.pop(0))
#-----3.count()-----
#该函数用于统计元素在列表中出现的次数
list1=[123,"Google","Runoob","Taobao",123]
print("123元素个数:",list1.count(123))
print("Runoob元素个数:",list1.count("runoob"))
#-----4.extend()-----
#list.extend(seq)用于在列表末尾一次性追加另一个序列中的多个值，seq可以是列表元组集合字典等元素列表
list1=["Google","Runoob","Taobao"]
list2=list(range(5))
list1.extend(list2)
print("扩展后列表=",list1)
#不同数据类型测试
language=["French","English","German"]
language_tuple=("Spanish","Portuguese")
language_set={"Chinese","Japanese"}
language.extend(language_tuple)
print("新列表:",language)
language.extend(language_set)
print("新列表:",language)
#当追加对象为字典时，仅将键(key)作为元素依次添加至原列表末尾
#-----5.index()&remove()-----
#list.index()函数用于从列表中找出某个值第一个匹配项的索引位置，找到时返回索引位置，没找到则抛出异常
#list.index(x,start,end)x为所查找对象，start和end分别为查找起始位与结束位
list1=["Google","Runoob","Taobao"]
print("Runoob索引值为",list1.index("Runoob"))
print("Taobao索引值为",list1.index("Taobao"))
list1=["Google","Runoob","Taobao","Facebook","QQ"]
print("Runoob索引值为",list1.index("Runoob",1))
#list.remove(obj)则是用于移除列表中某个值(即为obj)的第一个匹配项
list1=["Google","Runoob","Taobao","Baidu"]
list1.remove("Taobao")
print("列表现在为:",list1)
list1.remove("Baidu")
print("列表现在为:",list1)

