#-----1.add()&update()-----
#均用于为集合添加元素，，添加类型不同，add()每次添加单个对象
fruits={"apple","banana","cherry"}
fruits.add("orange")
print(fruits)
fruits.add("apple")                 #已存在元素不做添加操作
print(fruits)
#update()可用于添加可迭代对象，但不是将可迭代对象本身加入，而是取出子元素逐一加入
fruits={"apple","banana","cherry"}
#fruits.update("orange")            #字符串属于可迭代对象，会被逐字母拆解后加入集合
#print(fruits)
fruits.update(["orange","grapes","coconut"])    #可使用列表或元组进行一层保护
print(fruits)
#因此也可以用来合并集合
set_a={1,2,3,4,5}
set_b={3,4,5,6,7}
set_a.update(set_b)
print(set_a)
#-----2.clear()-----
#该函数用于移除集合中的所有元素，但比起del会保留容器及所在内存
fruits={"apple","banana","cherry"} 
fruits.clear()
print(fruits) 
#-----3.copy()-----
#该函数用于浅拷贝集合，返回值为拷贝的集合
#(但因为集合内部即便嵌套其他数据结构，也只能嵌套可哈希的不能修改的结构，因此等于深拷贝)
sites={"Google","Runoob","Taobao"}
x=sites.copy()
print(x)
#-----4.remove()&discard()&pop()-----
#这三个函数均用于移除集合元素，但discard()比起remove()在移除不存在元素时不报错，而pop()则是"随机"移除
fruits={"apple","banana","cherry"}
fruits.remove("banana")
print(fruits)
fruits.discard("cherry")
print(fruits)
print(f"移除对象为:{fruits.pop()},移除后的集合为:{fruits}")     #因为删的只剩一个了，所以体现不出随机
#
#-----5.集合运算函数们(上)-----
#这里的函数均用于进行集合运算，返回值也为对应的运算结果，从差集计算开始
#set.difference(set)用于返回集合的差集，即返回的集合元素包含在第一个集合中，但不包含在第二个集合中
x={"apple","banana","cherry"}
y={"google","microsoft","apple"}
print(f"x.difference(y)={x.difference(y)}")
#difference_update(set)用于移除两个元素中均存在的元素，比起原版，修改为在原有集合中移除元素，无返回值
x={"apple","banana","cherry"}
y={"google","microsoft","apple"}
x.difference_update(y)
print(f"x={x}")
#set.intersection(set1,set...)用于返回两个或更多集合中都包含的元素，即交集
#参数为要查找相同元素的集合，返回值为一新集合，该集合的元素包含在所有集合中
x={"apple","banana","cherry"}
y={"google","runoob","apple"}
print(f"x.intersection(y)={x.intersection(y)}")
#多集合场景下
x={"a","b","c"}
y={"c","d","e"}
z={"f","g","c"}
print(f"x.intersection(y,z)={x.intersection(y,z)}")
#intersection.update()则用于移除集合中所有不存在于参数集合中的元素
x={"apple","banana","cherry"}
y={"google","runoob","apple"}
x.intersection_update(y)
print(f"x={x}")
#多集合场景下
x={"a","b","c"}
y={"c","d","e"}
z={"f","g","c"}
x.intersection(y,z)
print(f"x={x}")
#其实几个函数的update版本质来讲，就是将原来的函数从返回新集合修改为了原地修改原集合